[versions]
springboot = "4.1.0"
springdependencymanagement = "1.1.7"
langchain4j = "1.18.1"
langgraph4j = "1.8.24"
flyway = "13.2.0"
postgres = "42.7.13"
jobrunr = "8.8.1"
junit = "6.1.3"
restassured = "6.0.1"
testcontainers = "2.0.5"
archunit = "1.5.0"

[libraries]
spring-boot-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-restclient = { group = "org.springframework.boot", name = "spring-boot-starter-restclient" }
spring-boot-data = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-flyway = { group = "org.springframework.boot", name = "spring-boot-starter-flyway" }
spring-boot-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }
spring-boot-jobrunr = { group = "org.jobrunr", name = "jobrunr-spring-boot-4-starter", version.ref = "jobrunr" }

langchain4j-bom = { group = "dev.langchain4j", name = "langchain4j-bom", version.ref = "langchain4j" }
langchain4j-core = { group = "dev.langchain4j", name = "langchain4j-core" }
langchain4j-ollama = { group = "dev.langchain4j", name = "langchain4j-ollama" }
langchain4j-openai = { group = "dev.langchain4j", name = "langchain4j-open-ai" }
langchain4j-anthropic = { group = "dev.langchain4j", name = "langchain4j-anthropic" }
langgraph4j-core = { group = "org.bsc.langgraph4j", name = "langgraph4j-core", version.ref = "langgraph4j" }

flyway-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }

restassured = { group = "io.rest-assured", name = "rest-assured", version.ref = "restassured" }

testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version = "1.21.4" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version = "1.21.4" }

archunit = { group = "com.tngtech.archunit", name = "archunit-junit5", version.ref = "archunit" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springdependencymanagement" }