[versions]
springboot = "4.1.0"
springdependencymanagement = "1.1.7"
langchain4j = "1.16.3"
langgraph4j = "1.8.19"
jackson = "2.19.0"
junit = "5.14.1"
restassured = "6.0.0"
testcontainers = "2.0.5"
archunit = "1.4.2"

[libraries]
spring-boot-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-boot-data = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-flyway = { group = "org.springframework.boot", name = "spring-boot-starter-flyway" }
spring-boot-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }

spring-boot-devtools = { group= "org.springframework.boot", name = "spring-boot-devtools"}

langchain4j-bom = { group = "dev.langchain4j", name = "langchain4j-bom", version.ref = "langchain4j" }
langchain4j-core = { group = "dev.langchain4j", name = "langchain4j-core" }
langchain4j-ollama = { group = "dev.langchain4j", name = "langchain4j-ollama" }
langchain4j-openai = { group = "dev.langchain4j", name = "langchain4j-open-ai" }
langchain4j-anthropic = { group = "dev.langchain4j", name = "langchain4j-anthropic" }
langgraph4j-core = { group = "org.bsc.langgraph4j", name = "langgraph4j-core", version.ref = "langgraph4j" }

jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

flyway-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
postgresql = { group = "org.postgresql", name = "postgresql" }

junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }

restassured = { group = "io.rest-assured", name = "rest-assured", version.ref = "restassured" }

testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "junit-jupiter", version = "1.21.4" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version = "1.21.4" }

archunit = { group = "com.tngtech.archunit", name = "archunit-junit5", version.ref = "archunit" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springboot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springdependencymanagement" }
